### ISSUE TITLE
Errors when an account is registered by another user

### ISSUE THREAD

**Issue by davidabian** [wikimedia/countervandalism-CVNBot#19]
When a user creates another user account, CVNBot reports twice that the first account was registered.

Real example of today (March, 14) on #cvn-wp-es:

```
20:49:09 <+CVNBot3> Usuario nuevo [[es:User:Fffgfdghfdgfdgf]] creado. Bloquear: http://es.wikipedia.org/wiki/Special:Blockip/Fffgfdghfdgfdgf
20:50:44 <+CVNBot3> Usuario nuevo [[es:User:Fffgfdghfdgfdgf]] creado. Bloquear: http://es.wikipedia.org/wiki/Special:Blockip/Fffgfdghfdgfdgf
```

While CVNBot3 should have reported:

```
20:49:09 <+CVNBot3> Usuario nuevo [[es:User:Fffgfdghfdgfdgf]] creado. Bloquear: http://es.wikipedia.org/wiki/Special:Blockip/Fffgfdghfdgfdgf
20:50:44 <+CVNBot3> Usuario nuevo [[es:User:Fffgfdghfdgfdg]] creado. Bloquear: http://es.wikipedia.org/wiki/Special:Blockip/Fffgfdghfdgfdg
```

(Note the final "f"; I know this is not the clearest example, but it is a real one, a vandalism.)

You can check these registrations on https://es.wikipedia.org/wiki/Especial:Registro/Fffgfdghfdgfdgf.

Thanks in advance.

**Comment by Krinkle** [comment]
@MarcoAurelioWM wrote at <https://github.com/countervandalism/CVNBot/issues/37>

> `User:A` is registered already and creates an account for `User:B`. CVNBot will however display that User:A has been created.
> 
> * Recent example: `<CVNBot5> New user [[m:User:JGulingan (WMF)]] created. Block: https://meta.wikimedia.org/wiki/Special:Blockip/JGulingan_%28WMF%29`
> * Real log: `(User creation log); 22:26 . . User account EYildrim (WMF) (talk | contribs | block) was created by JGulingan (WMF) (talk | contribs | block) and password was sent by email ‎(WMF Fellow)`
> * Suggested output: `New user $new_user was created by $creator. Block: $blocklink`
> 
> Thank you.

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T327126>.
