### ISSUE TITLE
Add user to admin list without removing from whitelist

### ISSUE THREAD

**Issue by ghost** [wikimedia/countervandalism-CVNBot#26]
Same as issue #18 (about bot list) also applies to the admin list. Thanks.

**Comment by MarcoAurelioWM** [comment]
The 'ghost' account is me with my old ID. Please referr any questions to me. Thanks.

**Comment by MarcoAurelioWM** [comment]
Came here to report this to see that I already did reported the issue 😃 
A workaround I sometimes use is to `CVNBot getadmins p=<wiki>` or `batchgetusers` although the later has made the bots to go down in the past thus I'm not using that often.

**Comment by ZIJony** [comment]
Any update on this!

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T327129>.
