### ISSUE TITLE
Allow a global bot list

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/countervandalism-CVNBot#35]
> CVNBot6: There are no global admins/bots. Specify a project with the p= parameter.

Please add support for a global bot list. Not only global bots exist, but sometimes it's good to have some individual temporary ignored on the bots to avoid flooding, like when we perform global renames.

Addition to this list should be posible without the need to remove the user from any other list he's into (see #18 & #26).

Thank you!

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T327132>.
