### ISSUE TITLE
Protection flags displayed inside article name

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/countervandalism-CVNBot#41]
`<CVNBot5> Admin [[m:User:Xaosflux]] Protected [[m:User talk:A-Chinese-Wikipedian ‎[edit=autoconfirmed] (expires 13:58, 23 August 2018 (UTC))‎[move=autoconfirmed] (expires 13:58, 23 August 2018 (UTC))]] "Persistent vandalism"`

the article closing `]]` tags should be at the end of the article name.

**Comment by rxywm** [comment]
Related with [this bug](https://phabricator.wikimedia.org/T20541)

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T327133>.
