### ISSUE TITLE
Greylist should not override Blacklist

### ISSUE THREAD

**Issue by revi** [wikimedia/countervandalism-CVNBot#43]
When blacklisted user (in this case, by block on other channel) matches greylist rule, that should not override blacklist.

Not sure if this is intended...

[<img height="400" src="https://user-images.githubusercontent.com/156867/37061471-80234a00-2148-11e8-844d-83f1ada86ef3.png" alt="image">](https://user-images.githubusercontent.com/156867/37061471-80234a00-2148-11e8-844d-83f1ada86ef3.png)

**Comment by rstular** [comment]
Does this issue still exist? After some testing, I was unable to reproduce it.

**Comment by Krinkle** [comment]
Presumed resolved. Feel free to report to <https://phabricator.wikimedia.org/tag/cvnbot/> if you encounter it again.
