### ISSUE TITLE
Broken CentralAuth URL on accounts created by others

### ISSUE THREAD

**Issue by MarcoAurelioWM** [wikimedia/countervandalism-CVNBot#55]
Spotted today:

`<CVNBot8> New user [[hr:User:Marijicaaa08]] created by [[hr:User:OR6667]]. CentralAuth: ${caurl}`

`CVNBot8` runs `CVNBot 1.22.0-beta.3` in `#cvn-sw`.

Related: #19 and #37.

Apparently comming from: https://github.com/countervandalism/CVNBot/blob/7710949a2b8095ccef9267e7b984851d5bb29cfa/src/CVNBot/Program.cs#L1141

**Comment by MarcoAurelioWM** [comment]
Accounts created by anonymous users are not being affected by this issue.

**Comment by Krinkle** [comment]
@MarcoAurelioWM Can you confirm whether this is still reproducible since we've deployed CVNBot 3.0?

**Comment by MarcoAurelioWM** [comment]
Certainly. Please allow me a day or two to check on IRC, if possible.
Thanks.
-- 
M. A.

**Comment by MarcoAurelioWM** [comment]
> @MarcoAurelioWM Can you confirm if this is still reproducible since we deployed CVNBot 3.0?

Apparently we're back at the old behaviour:

`<CVNBot5> New user [[m:User:JCabanero (WMF)]] created. Block: https://meta.wikimedia.org/wiki/Special:Block/JCabanero_%28WMF%29` for `#cvn-meta`

`<CVNBot6> New user [[m:User:JCabanero (WMF)]] created. CentralAuth: https://meta.wikimedia.org/wiki/Special:CentralAuth/JCabanero_%28WMF%29` for `#cvn-sw`

Actual log on Meta-Wiki: [here](https://meta.wikimedia.org/wiki/Special:Redirect/logid/33300773).

CVNBot5: `CVNBot 1.22.0-beta.3`

CVNBot6: `CVNBot 1.22.0-beta.3`

Regards.

**Comment by Naleksuh** [comment]
This is still happening 2020-06-22. Also, plus signs have been around longer than ${} has

**Comment by Krinkle** [comment]
Moved to <https://phabricator.wikimedia.org/T327127>.
